name: CI/CD with Vault (self-hosted)

on:
  push:
    branches: ["main"]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  TAG: 1.0.${{ github.run_number }}

jobs:

  build-deploy:
    runs-on: self-hosted

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    # =========================
    # 1. LOGIN TO VAULT (AppRole)
    # =========================
    - name: Login to Vault
      id: vault
      run: |
        export VAULT_ADDR=http://192.168.0.230:8200

        TOKEN=$(curl -s --request POST \
          --data "{\"role_id\":\"${{ secrets.VAULT_ROLE_ID }}\",\"secret_id\":\"${{ secrets.VAULT_SECRET_ID }}\"}" \
          $VAULT_ADDR/v1/auth/approle/login | jq -r .auth.client_token)

        echo "VAULT_TOKEN=$TOKEN" >> $GITHUB_ENV

    # =========================
    # 2. GET DOCKER CREDS FROM VAULT
    # =========================
    - name: Get Docker creds
      run: |
        curl -s \
          --header "X-Vault-Token: $VAULT_TOKEN" \
          http://127.0.0.1:8200/v1/secret/data/docker > vault.json

        echo "DOCKER_USERNAME=$(jq -r .data.data.username vault.json)" >> $GITHUB_ENV
        echo "DOCKER_PASSWORD=$(jq -r .data.data.password vault.json)" >> $GITHUB_ENV

    # =========================
    # 3. DOCKER LOGIN
    # =========================
    - name: Docker login
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    # =========================
    # 4. BUILD BACKEND
    # =========================
    - name: Build backend
      run: |
        docker build -t $DOCKER_USER/backend:$TAG apps/backend
        docker push $DOCKER_USER/backend:$TAG

    # =========================
    # 5. BUILD FRONTEND
    # =========================
    - name: Build frontend
      run: |
        docker build -t $DOCKER_USER/frontend:$TAG apps/frontend
        docker push $DOCKER_USER/frontend:$TAG

    # =========================
    # 6. DEPLOY TO K3S
    # =========================
    - name: Deploy to K3s
      run: |
        kubectl set image deployment/backend \
          backend=$DOCKER_USER/backend:$TAG \
          -n devops-app

        kubectl set image deployment/frontend \
          frontend=$DOCKER_USER/frontend:$TAG \
          -n devops-app

        kubectl rollout status deployment/backend -n devops-app
        kubectl rollout status deployment/frontend -n devops-app
