name: DevOps CI/CD Pipeline

on:
  push:
    branches: ["main"]

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  TAG: 1.0.${{ github.run_number }}

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # =========================
      # Docker login
      # =========================
      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # =========================
      # Build backend
      # =========================
      - name: Build backend
        run: |
          docker build \
            -t $DOCKER_USER/backend:$TAG \
            apps/backend

          docker push $DOCKER_USER/backend:$TAG

      # =========================
      # Build frontend
      # =========================
      - name: Build frontend
        run: |
          docker build \
            -t $DOCKER_USER/frontend:$TAG \
            apps/frontend

          docker push $DOCKER_USER/frontend:$TAG


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to k3s via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.K8S_HOST }}
          username: ${{ secrets.K8S_USER }}
          key: ${{ secrets.K8S_SSH_KEY }}
          script: |

            set -e

            DOCKER_USER="${{ secrets.DOCKER_USERNAME }}"
            TAG="1.0.${{ github.run_number }}"

            echo "Deploying version $TAG"

            # =========================
            # Backend deploy
            # =========================
            kubectl set image deployment/backend \
              backend=$DOCKER_USER/backend:$TAG \
              -n devops-app

            # =========================
            # Frontend deploy
            # =========================
            kubectl set image deployment/frontend \
              frontend=$DOCKER_USER/frontend:$TAG \
              -n devops-app

            # =========================
            # Rollout status check
            # =========================
            kubectl rollout status deployment/backend -n devops-app
            kubectl rollout status deployment/frontend -n devops-app
